### PR TITLE
update to use yaml-cpp0.5 api

### PR DESCRIPTION
**Pull request by ClintLiddick**
Update YAML code. Please check and make sure I didn't do anything stupid (though it is working on herb).

### CODE REVIEW

**Comment by mkoval** [comment]
In general, we try to maintain backwards compatibility with Hydro when possible. But we only use this code internally, so it's probably okay to violate that rule here.

**Comment by ClintLiddick** [comment]
I saw some code does a version check on a yaml-cpp const, I can do the same here.

**Comment by mkoval** [comment]
I have an example of the version test in [this `CMakeLists.txt`](https://github.com/personalrobotics/kenv/blob/feature/indigo/box2d_kenv/CMakeLists.txt#L30) file. It defines a `YAMLCPP_NEWAPI` macro that you can test for with `#ifdef`.

Note that **this definition is passed on the command line** with `-D` flag, so you should not **query it in headers**. If you need this, then you should use CMake to generate a configuration header with a `#define` statement in it.

**Comment by ClintLiddick** [comment]
@mkoval Take a look. This works for me with indigo, and is the same code as before so should work with hydro.

**Comment by mkoval** [comment]
LGTM. Thanks!

**Pull request merged**
